// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Safe is an autogenerated mock type for the Safe type
type Safe struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *Safe) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSecretName provides a mock function with given fields:
func (_m *Safe) GetSecretName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetName provides a mock function with given fields: name
func (_m *Safe) SetName(name string) {
	_m.Called(name)
}
